# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window'.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label0 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label0.setFont(font)
        self.label0.setObjectName("label0")
        self.horizontalLayout_3.addWidget(self.label0)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelbat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelbat.setFont(font)
        self.labelbat.setObjectName("labelbat")
        self.horizontalLayout.addWidget(self.labelbat)
        self.batle = QtWidgets.QLineEdit(self.centralwidget)
        self.batle.setObjectName("batle")
        self.horizontalLayout.addWidget(self.batle)
        self.labelbow = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelbow.setFont(font)
        self.labelbow.setObjectName("labelbow")
        self.horizontalLayout.addWidget(self.labelbow)
        self.bowle = QtWidgets.QLineEdit(self.centralwidget)
        self.bowle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bowle.setInputMask("")
        self.bowle.setReadOnly(False)
        self.bowle.setObjectName("bowle")
        self.horizontalLayout.addWidget(self.bowle)
        self.labelar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelar.setFont(font)
        self.labelar.setObjectName("labelar")
        self.horizontalLayout.addWidget(self.labelar)
        self.arle = QtWidgets.QLineEdit(self.centralwidget)
        self.arle.setObjectName("arle")
        self.horizontalLayout.addWidget(self.arle)
        self.labelwk = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelwk.setFont(font)
        self.labelwk.setObjectName("labelwk")
        self.horizontalLayout.addWidget(self.labelwk)
        self.wkle = QtWidgets.QLineEdit(self.centralwidget)
        self.wkle.setObjectName("wkle")
        self.horizontalLayout.addWidget(self.wkle)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelptav = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelptav.setFont(font)
        self.labelptav.setObjectName("labelptav")
        self.horizontalLayout_4.addWidget(self.labelptav)
        self.ptavle = QtWidgets.QLineEdit(self.centralwidget)
        self.ptavle.setObjectName("ptavle")
        self.horizontalLayout_4.addWidget(self.ptavle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labelptu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelptu.setFont(font)
        self.labelptu.setObjectName("labelptu")
        self.horizontalLayout_4.addWidget(self.labelptu)
        self.ptule = QtWidgets.QLineEdit(self.centralwidget)
        self.ptule.setObjectName("ptule")
        self.horizontalLayout_4.addWidget(self.ptule)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.batrb = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.batrb.setFont(font)
        self.batrb.setObjectName("batrb")
        self.horizontalLayout_5.addWidget(self.batrb)
        self.bowrb = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bowrb.setFont(font)
        self.bowrb.setObjectName("bowrb")
        self.horizontalLayout_5.addWidget(self.bowrb)
        self.arrb = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.arrb.setFont(font)
        self.arrb.setObjectName("arrb")
        self.horizontalLayout_5.addWidget(self.arrb)
        self.wkrb = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wkrb.setFont(font)
        self.wkrb.setObjectName("wkrb")
        self.horizontalLayout_5.addWidget(self.wkrb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.labeltn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltn.setFont(font)
        self.labeltn.setObjectName("labeltn")
        self.horizontalLayout_5.addWidget(self.labeltn)
        self.tnle = QtWidgets.QLineEdit(self.centralwidget)
        self.tnle.setObjectName("tnle")
        self.horizontalLayout_5.addWidget(self.tnle)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelavp = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelavp.setFont(font)
        self.labelavp.setObjectName("labelavp")
        self.horizontalLayout_8.addWidget(self.labelavp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.labelsp = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelsp.setFont(font)
        self.labelsp.setObjectName("labelsp")
        self.horizontalLayout_8.addWidget(self.labelsp)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listmain1 = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.listmain1.setFont(font)
        self.listmain1.setObjectName("listmain1")
        self.horizontalLayout_6.addWidget(self.listmain1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.listmain2 = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.listmain2.setFont(font)
        self.listmain2.setObjectName("listmain2")
        self.horizontalLayout_6.addWidget(self.listmain2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 26))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionSAVE_Team)
        self.menuManage_Teams.addAction(self.actionEVALUATE_Team)
        self.menuManage_Teams.addAction(self.actionExit)
        self.menuManage_Teams.addAction(self.actionHelp)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label0.setText(_translate("MainWindow", "Your Selections"))
        self.labelbat.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.labelbow.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.labelar.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.labelwk.setText(_translate("MainWindow", "Wicket-Keepers (WK)"))
        self.labelptav.setText(_translate("MainWindow", "Points Available"))
        self.labelptu.setText(_translate("MainWindow", "Points Used"))
        self.batrb.setText(_translate("MainWindow", "BAT"))
        self.bowrb.setText(_translate("MainWindow", "BOW"))
        self.arrb.setText(_translate("MainWindow", "AR"))
        self.wkrb.setText(_translate("MainWindow", "WK"))
        self.labeltn.setText(_translate("MainWindow", "Team Name"))
        self.labelavp.setText(_translate("MainWindow", "          Available Players"))
        self.labelsp.setText(_translate("MainWindow", "Selected players"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionNEW_Team.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionOPEN_Team.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionSAVE_Team.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))
        self.actionEVALUATE_Team.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Tab"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
